# Generated by Django 2.2 on 2021-10-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokerboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of Pokerboard', max_length=20, unique=True)),
                ('description', models.CharField(help_text='Description of POkerboard', max_length=100)),
                ('configuration', models.IntegerField(choices=[(1, 'Series'), (2, 'Even'), (3, 'Odd'), (4, 'Fibonacci')], default=1, help_text='Estimation type')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Started'), (3, 'Ended')], default=1)),
            ],
        ),
    ]
