# Generated by Django 2.2 on 2021-10-24 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pokerboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the session.', max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'ongoing'), (1, 'hasended')], default=0, help_text='Session ongoing or ended')),
                ('pokerboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokerboard.Pokerboard')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(help_text='Ticket ID imported from JIRA.', max_length=100, unique=True)),
                ('order', models.PositiveSmallIntegerField(help_text='Rank of ticket.')),
                ('estimation_date', models.DateField(blank=True, help_text='Date on which ticket was estimated', null=True)),
                ('status', models.IntegerField(choices=[(0, 'notstarted'), (0, 'ongoing'), (1, 'hasended')], default=0, help_text='Default ticket status is not started.')),
                ('session', models.ForeignKey(help_text='Pokerboard to which ticket belongs.', on_delete=django.db.models.deletion.CASCADE, to='session.Session')),
            ],
        ),
        migrations.CreateModel(
            name='UserEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimation_duration', models.DurationField(help_text='Duration for voting(in secs)')),
                ('estimate', models.PositiveIntegerField(help_text='Value of estimate done by the user.')),
                ('ticket', models.ForeignKey(help_text='Ticket to which estimate belongs.', on_delete=django.db.models.deletion.CASCADE, to='session.Ticket')),
                ('user', models.ForeignKey(help_text='User which has estimated the ticket.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
