# Generated by Django 2.2 on 2021-10-29 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='pokerboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session', to='pokerboard.Pokerboard'),
        ),
    ]
