# Generated by Django 2.2 on 2021-10-31 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20211029_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='time_started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
