# Generated by Django 2.2 on 2021-10-05 06:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(
                help_text='Members of the group', to=settings.AUTH_USER_MODEL),
        ),
    ]
