# Generated by Django 2.2 on 2021-11-12 07:12

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0002_auto_20211111_0651'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'created_by')},
        ),
    ]
