# Generated by Django 2.2 on 2021-10-05 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.IntegerField(choices=[(0, 'PLAYER'), (1, 'MANAGER'), (2, 'SPECTATOR')], default=0, help_text='Default user role is player')),
                ('is_accepted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Pokerboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of Pokerboard.', max_length=50)),
                ('description', models.CharField(help_text='Description of POkerboard.', max_length=100)),
                ('configuration', models.IntegerField(choices=[(1, 'Series'), (2, 'Even'), (3, 'Odd'), (4, 'Fibonacci')], default=1, help_text='Estimation type.')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Created'), (2, 'Started'), (3, 'Ended')], default=1, help_text='Default pokerboard status is created.')),
            ],
        ),
        migrations.CreateModel(
            name='PokerboardUserMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.IntegerField(choices=[(0, 'PLAYER'), (1, 'MANAGER'), (2, 'SPECTATOR')], default=0, help_text='Default user role is player.')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(help_text='Ticket ID imported from JIRA.', max_length=100)),
                ('order', models.PositiveSmallIntegerField(help_text='Rank of ticket.')),
                ('estimation_date', models.DateField()),
                ('status', models.IntegerField(choices=[(0, 'notstarted'), (0, 'ongoing'), (1, 'hasended')], default=0, help_text='Default ticket status is not started.')),
            ],
        ),
        migrations.CreateModel(
            name='UserEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken_to_estimate', models.IntegerField(default=0, help_text='Duration for voting(in secs)')),
                ('estimate', models.PositiveIntegerField(help_text='Value of estimate done by the user.')),
                ('ticket', models.ForeignKey(help_text='Ticket to which estimate belongs.', on_delete=django.db.models.deletion.CASCADE, to='pokerboard.Ticket')),
            ],
        ),
    ]
