# Generated by Django 2.2 on 2021-10-25 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
