# Generated by Django 2.2 on 2021-10-30 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboard to which ticket belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='pokerboard.Pokerboard'),
        ),
    ]
