# Generated by Django 2.2 on 2021-10-22 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invite',
            name='is_accepted',
        ),
        migrations.AddField(
            model_name='invite',
            name='status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'DECLINED')], default=0, help_text='Default status of the invite.'),
        ),
        migrations.AddField(
            model_name='session',
            name='title',
            field=models.CharField(default='title', help_text='Title of the session.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invite',
            name='user_role',
            field=models.IntegerField(choices=[(0, 'PLAYER'), (1, 'SPECTATOR')], default=0, help_text='Default user role is player.'),
        ),
    ]
