# Generated by Django 2.2 on 2021-10-07 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokerboard', '0003_auto_20211007_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(help_text='Ticket ID imported from JIRA.', max_length=100, unique=True),
        ),
    ]
