# Generated by Django 2.2 on 2021-10-26 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokerboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_role', models.IntegerField(default=0, help_text='Default user role is player.')),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'DECLINED')], default=0, help_text='Default status of the invite.')),
                ('group', models.ForeignKey(help_text='Group which is invited.', null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('pokerboard', models.ForeignKey(help_text='Pokerboard of which invite has been sent.', on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='pokerboard.Pokerboard')),
                ('user', models.ForeignKey(help_text='User which is invited.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
