# Generated by Django 2.2 on 2021-11-11 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pokerboard', '0001_initial'),
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Time at which object was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Time at which object was updated')),
                ('email', models.EmailField(help_text='Email of user which is invited.', max_length=254)),
                ('user_role', models.IntegerField(choices=[(0, 'PLAYER'), (1, 'SPECTATOR')], default=0, help_text='Default user role is player.')),
                ('status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'ACCEPTED'), (2, 'DECLINED')], default=0, help_text='Default status of the invite.')),
                ('group', models.ForeignKey(help_text='Group which is invited.', null=True, on_delete=django.db.models.deletion.CASCADE, to='group.Group')),
                ('pokerboard', models.ForeignKey(help_text='Pokerboard of which invite has been sent.', on_delete=django.db.models.deletion.CASCADE, to='pokerboard.Pokerboard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
