# Generated by Django 2.2 on 2021-11-11 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invite', '0001_initial'),
        ('pokerboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='pokerboard',
            field=models.ForeignKey(help_text='Pokerboard of which invite has been sent.', on_delete=django.db.models.deletion.CASCADE, to='pokerboard.Pokerboard'),
        ),
    ]
